version: '2'

services:

  quotes:
    container_name: quotes
    build:
      context: quotes
    ports:
      - "9000:9000"
    environment:
      - NETFYFFE_HARVEST=http://localhost:9001
    volumes:
      - ./quotes:/var/app

  portfolio:
    container_name: portfolio
    build:
      context: portfolio
    ports:
      - "9000:9000"
    depends_on:
      - "quotes"
    environment:
      - NETFYFFE_QUOTES=http://localhost:9000
    volumes:
      - ./portfolio:/var/app
