version: '2'

services:

  quotes:
    container_name: quotes
    build:
      context: quotes
    ports:
      - "9000:9000"
    environment:
      - NETFYFFE_HARVEST=http://harvest:9001
    volumes:
      - ./quotes/src:/var/app/src
      - ./quotes/seeds:/var/app/seeds
      - ./common:/var/app/src/common
    command: npm run dev

  harvest:
    container_name: harvest
    build:
      context: harvest
    ports:
      - "9001:9001"
    volumes:
      - ./harvest/src:/var/app/src
      - ./common:/var/app/src/common
    command: npm run dev

  portfolio:
    container_name: portfolio
    build:
      context: portfolio
    ports:
      - "9002:9002"
    volumes:
      - ./portfolio/src:/var/app/src
      - ./common:/var/app/src/common
    command: npm run dev

  ui:
    container_name: ui
    build:
      context: ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/var/app/src
    command: npm run dev
