version: '2'

services:

  quotes:
    container_name: quotes
    build:
      context: quotes
    ports:
      - "9000:9000"
    environment:
      - NETFYFFE_HARVEST=http://localhost:9001
    volumes:
      - ./quotes/src:/var/app/src
      - ./common:/var/app/src/common
