
exports.seed = function(knex, Promise) {
  return knex('tickers').del()
    .then(function () {
      return knex('tickers').insert([
        {name: "CapMan Plc B", ticker: "HEL:CAPMAN", currency: "EUR", country: "FIN"},
        {name: "eQ Oyj", ticker: "HEL:EQV1V", currency: "EUR", country: "FIN"},
        {name: "Keskisuomalainen", ticker: "HEL:KSLAV", currency: "EUR", country: "FIN"},
        {name: "Kesko B", ticker: "HEL:KESBV", currency: "EUR", country: "FIN"},
        {name: "Nordea Bank AB (publ) FDR", ticker: "HEL:NDA1V", currency: "EUR", country: "FIN"},
        {name: "Norvestia Plc", ticker: "HEL:NORVE", currency: "EUR", country: "FIN"},
        {name: "Ramirent", ticker: "HEL:RMR1V", currency: "EUR", country: "FIN"},
        {name: "Siili Solutions Oyj", ticker: "HEL:SIILI", currency: "EUR", country: "FIN"},
        {name: "Telia Company", ticker: "HEL:TELIA1", currency: "EUR", country: "FIN"},
        {name: "Sampo", ticker: "HEL:SAMPO", currency: "EUR", country: "FIN"},
        {name: "VanEck Russian Small Cap", ticker: "NYSEARCA:RSXJ", currency: "USD", country: "RUS"},
        {name: "Vanguard IT Index Fund", ticker: "NYSEARCA:VGT", currency: "USD", country: "USA"},
        {name: "VanEck EM High Yield", ticker: "NYSEARCA:HYEM", currency: "USD", country: "EM"},
        {name: "Armour REIT", ticker: "NYSE:ARR", currency: "USD", country: "USA"},
        {name: "Arlington REIT", ticker: "NYSE:AI", currency: "USD", country: "USA"},
        {name: "Lehto Group", ticker: "HEL:LEHTO", currency: "EUR", country: "FIN"},
        {name: "NY Mortage Trust REIT", ticker: "NASDAQ:NYMT", currency: "USD", country: "USA"},
        {name: "Realty Income REIT", ticker: "NYSE:O", currency: "USD", country: "USA"},
        {name: "UPM", ticker: "HEL:UPM", currency: "EUR", country: "FIN"},
        {name: "Weyerhaeuser", ticker: "NYSE:WY", currency: "USD", country: "USA"},
        {name: "First Trust ISE Global Wind Energy ETF", ticker: "NYSEARCA:FAN", currency: "USD", country: "EUR"},
        {name: "Nokia Corporation", ticker: "HEL:NOKIA", currency: "EUR", country: "FIN"},
        {name: "Käteinen €", ticker: "X:EUR", currency: "EUR", country: "EUR"},
        {name: "HCP Inc", ticker: "NYSE:HCP", currency: "USD", country: "USA"},
        {name: "Neste", ticker: "HEL:NESTE", currency: "EUR", country: "FIN"},
        {name: "Golar LNG Partners LP", ticker: "NASDAQ:GMLP", currency: "USD", country: "USA"},
        {name: "First Trust Technology Divident", ticker: "NASDAQ:TDIV", currency: "USD", country: "USA"},
        {name: "IBM", ticker: "NYSE:IBM", currency: "USD", country: "USA"},
        {name: "Intel", ticker: "NASDAQ:INTC", currency: "USD", country: "USA"},
        {name: "United Bankers", ticker: "X:UB", currency: "EUR", country: "FIN"},
        {name: "Fortum Corporation", ticker: "HEL:FUM1V", currency: "EUR", country: "FIN"},
        {name: "Okmetic Oyj", ticker: "X:OKM1V", currency: "EUR", country: "FIN"},
        {name: "Metso Corporation", ticker: "HEL:METSO", currency: "EUR", country: "FIN"},
        {name: "Orava REIT", ticker: "HEL:OREIT", currency: "EUR", country: "FIN"},
        {name: "Orava Asuntorahasto uudet", ticker: "HEL:OREITN0116", currency: "EUR", country: "FIN"},
        {name: "ishares Gold Trust", ticker: "NYSEARCA:IAU", currency: "USD","country": "N/A"},
        {name: "Wärtsilä Corporation", ticker: "HEL:WRT1V", currency: "EUR", country: "FIN"},
        {name: "Caverion Oyj", ticker: "HEL:CAV1V", currency: "EUR", country: "FIN"},
        {name: "Vincit Group Oyj", ticker: "X:VINCIT", currency: "EUR", country: "FIN"},
        {name: "Tesla Motors, Inc.", ticker: "NASDAQ:TSLA", currency: "USD", country: "USA"},
        {name: "Wulff Group Plc", ticker: "HEL:WUF1V", currency: "EUR", country: "FIN"},
        {name: "Nordnet Superfondet Norge", ticker: "X:SUPNOR", currency: "NOK", country: "NOR"},
        {name: "Nordnet Superfondet Denmark", ticker: "X:SUPDEN", currency: "DKK", country: "DEN"},
        {name: "Nordnet Superfonden Sverige", ticker: "X:SUPSVE", currency: "SEK", country: "SWE"},
        {name: "Nordnet Superrahasto Suomi", ticker: "X:SUPFIN", currency: "EUR", country: "FIN"},
        {name: "X-Tr. EM Liquid Euro Bond", ticker: "FRA:DXSU", currency: "EUR", country: "EM"},
        {name: "AstraZeneca Plc", ticker: "STO:AZN", currency: "SEK", country: "SWE"},
        {name: "Novo Nordisk A/S", ticker: "CPH:NOVO-B", currency: "DKK", country: "DEN"},
        {name: "Market Vectors Steel", ticker: "NYSEARCA:SLX", currency: "USD", country: "USA"},
        {name: "E.ON SE", ticker: "FRA:EOAN", currency: "EUR", country: "GER"},
        {name: "Global X MSCI Nigeria", ticker: "NYSEARCA:NGE", currency: "USD", country: "NGA"},
        {name: "Global X Robotics & A.I.", ticker: "NASDAQ:BOTZ", currency: "USD", country: "JAP"},
        {name: "SPDR S&P 600 Small Cap Value", ticker: "NYSEARCA:SLYV", currency: "USD", country: "USA"},
        {name: "iShares Japan Small Cap", ticker: "FRA:IUS4", currency: "EUR", country: "JAP"}
      ]);
    });
};
